version: "3"

services:
  ddaemon-webapp:
    image: ddaemon-webapp
    container_name: ddaemon-webapp
    volumes:
      - ./static:/home/node/app/backend/static
    environment:
      MY_VAR: test
    ports:
     - "8081:8081"
